config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "users/registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "users#index"

  resources :users do
  	resources :attachments
  end

  resources :attachments, only: [:download] do
  	get "/download", to: "attachments#download"
  end
end

app/models/attachment.rb
class Attachment
  include Mongoid::Document

  mount_uploader :attachment, AttachmentUploader

  belongs_to :user, inverse_of: :user

  validates_presence_of :attachment

  field :content_type
  field :filename
end

app/models/user.rb
class User
  include Mongoid::Document

  has_many :attachments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  field :first_name,         type: String 
  field :last_name,          type: String

  validates_presence_of :first_name, :last_name  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  include CarrierWave::Uploader::Download
  def index
    @attachments = Attachment.all
    redirect_to root_path
  end

  def create
    @user = User.find(params[:user_id])
    attachment = @user.attachments.new(attachment_params)
    content_type = attachment.attachment.content_type
    filename = attachment.attachment.filename
    if attachment.save
      attachment.update!(content_type: content_type, filename: filename)
      redirect_to root_path
    else
      @attachments = Attachment.all
      @errors = attachment.errors.full_messages
      render "users/index"
    end
  end

  def download
    attachment = Attachment.find(params[:attachment_id])
    file = open(attachment.attachment.url).read
    send_data file, filename: File.basename(attachment.attachment.path), type: attachment.content_type
  end

  private

  def attachment_params
    params.require(:attachment).permit(:attachment)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def index
    @attachments = Attachment.all.reverse
  end

  def show
  end

  private

  def set_user
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FileUploader</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.slim
- if user_signed_in?
  .jumbotron
    h5.center
      | Hello, 
      = current_user.first_name + "! "
      | Not you? 
      = link_to "Log out", destroy_user_session_path, method: :delete

    - if @errors
      - @errors.each do |e|
        = e


    = simple_form_for([@user, Attachment.new]) do |f|
      .file-form
        .file-field.input-field
          .btn
            <span>File</span>
            = f.file_field :attachment
          .file-path-wrapper
            = f.text_field :attachment_file_name, class: "file-path", value: ""
        = f.submit "LOAD", class: "btn green right", style: "margin-left: 25px; margin-top: 15px; padding-top: 10px; padding-bottom: 10px; height: 54px;"
    td  

    h4.all-files
      | All Files
    hr

    table
      thead
        tr
          th 
            | User
          th
            | File Name
          th.right
            | Download
      tbody
        - if @attachments
          - @attachments.each do |a|
            tr
              td
                = a.user.first_name + " "
                = a.user.last_name
              td
                span.tooltipped data-position="bottom" data-delay="50" data-tooltip=a.attachment.url
                  = a.filename
              td
                = link_to "Download", attachment_download_path(a.id), class: "right"

- else

  .jumbotron.center-align
    <h1>Hello!</h1>
    <p>This is a simple file uploader. You need to login or register to use it.</p>

      = link_to "Log In", new_user_session_path, class: "btn", style: "margin-bottom: 10px"
    br
      = link_to "Sign Up", new_user_registration_path, class: "btn teal darken-2"